### ISSUE TITLE
Question about hex notation

### ISSUE THREAD

**Issue by solarjoe** [adafruit/Adafruit_CircuitPython_MAX31856#16]
Hello,

I am trying to port your driver to work with spidev on a Raspberry Pi.
If you don't mind, I have two questions that I can't figure out:

1. In [`_read_register()`](https://github.com/adafruit/Adafruit_CircuitPython_MAX31856/blob/main/adafruit_max31856.py#L286) what is the operation `address & 0x7F` about?
2. In [`_write_u8()`](https://github.com/adafruit/Adafruit_CircuitPython_MAX31856/blob/main/adafruit_max31856.py#L294) what are the operations `& 0xFF` for?

Hope to hear from you,
Joe

**Comment by dastels** [comment]
The `&` operator is binary AND. 
`address & 0x7F` ensures that the value (the result of the &) is in a 7-bit number, i.e. in the range 0-127. It sets to 0 any binary digits other than the lowest 7, which it leaves uneffected. Similarly `& 0xFF` ensures an 8-bit value, in the range 0-255.

So `170 & 0x7F` is '0xAA & 0x7F' in hex, which is `0b10101010 & 0b01111111` in binary with results in `0b00101010`, i.e. `0x2A`, i.e. 42

**Comment by solarjoe** [comment]
Thanks for your reply, I think I got it now. 
The address of the write registers for MAX31856 writing are `0x80` higher than the ones for reading.
So using the `0x7F` keeps you from defining them separately. Smart, I like it :)
