### ISSUE TITLE
Missing feature: 50/60Hz noise filtering

### ISSUE THREAD

**Issue by eirinnm** [adafruit/Adafruit_CircuitPython_MAX31856#18]
The MAX31656 contains a mains frequency notch filter, set to 60Hz by default. This should be changed for applications in 50Hz regions. The arduino library for this breakout board allows for selecting 50Hz:

https://github.com/adafruit/Adafruit_MAX31856/blob/master/Adafruit_MAX31856.cpp#L189

However this feature is missing in the Circuitpython library.

**Comment by ladyada** [comment]
wanna try adding it? :)

**Comment by eirinnm** [comment]
Yes I can do it! Will file a PR soon :)

**Comment by ladyada** [comment]
sweet @tekktrik can help if you have any CI/implementation questions!
